# نام این اتوماسیون
name: Daily Telegram Post Bot

on:
  # این گزینه به شما اجازه می‌دهد که به صورت دستی هم ربات را فعال کنید
  workflow_dispatch:
  schedule:
    # این بخش زمان‌بندی را مشخص می‌کند
    # کد زیر یعنی هر روز ساعت ۹ صبح به وقت جهانی (UTC)
    # ساعت ۱۲:۳۰ ظهر به وقت ایران
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # دریافت کدها از ریپازیتوری
      - name: Checkout repository
        uses: actions/checkout@v4

      # نصب پایتون
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # نصب کتابخانه‌های مورد نیاز
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # اجرای کد اصلی پایتون
      - name: Run Python script
        env:
          # ارسال کلیدهای امن به کد پایتون
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
        run: python main.py
